src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['event','artist'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['event','artist'])]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(['event','artist'])]
    private ?\DateTimeInterface $date = null;

    //clé étrangére référant l'artiste concerné
    #[ORM\ManyToOne(targetEntity: Artist::class, inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: true)]
    #[Groups(['event'])]
    private ?Artist $artist = null;

    //reférence les utilisateurs qui ont ajouté l'évent

    #[Groups(['event'])]
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'events')]
    private Collection $Follower;


    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'createdEvents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $creator = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): static
    {
        $this->artist = $artist;

        return $this;
    }

    public function getFollower(): Collection
    {
        return $this->Follower;
    }

    public function addUser(User $user): static
    {
        if (!$this->Follower->contains($user)) {
            $this->Follower->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static{
        $this->Follower->removeElement($user);
        return $this;

    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }
}

src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $artiste = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getArtiste(): ?string
    {
        return $this->artiste;
    }

    public function setArtiste(string $artiste): static
    {
        $this->artiste = $artiste;

        return $this;
    }
}

src/Controller/EventsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Artist;
use App\Entity\Event;
use App\Form\EventFormType;
use App\Form\ModifyEventFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventsController extends AbstractController
{
    #[Route('/event', name: 'app_event')]
    public function events(Request $request,EntityManagerInterface $entityManager): Response
    {

        $startDate = $request->query->get('start_date');
        $endDate = $request->query->get('end_date');

        if ($startDate && $endDate) {
            $event = $entityManager->getRepository(Event::class)->findByDateRange(new \DateTime($startDate), new \DateTime($endDate));
        } else {
            $event = $entityManager->getRepository(Event::class)->findAll();
        }

        return $this->render('event/event.html.twig', [
            'events' => $event,
        ]);
    }

    #[Route('/event/create', name: 'app_create_event')]
    public function event(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(type: EventFormType::class, data: $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $event->setCreator($this->getUser());
            $entityManager->persist($event);
            $entityManager->flush();
            return $this->redirectToRoute('app_event');
        }
        return $this->render('event/create.html.twig', [
            'form' => $form,
        ]);
    }


    #[Route('/event/{{id}}/delete', name: 'app_delete_event')]
    public function delete(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $events = $entityManager->getRepository(Event::class)->find($id);

        $entityManager->remove($events);
        $entityManager->flush();
        return $this->redirectToRoute('app_event');
    }


    #[Route('/event/{{id}}/modify', name: 'app_modify_event')]
    public function modify(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $events = $entityManager->getRepository(Event::class)->find($id);
        //safety si un utilisateur essaie de passer par l'url avec une id random
        if ($this->getUser()->getId() !== $events->getCreator()->getId()) {
            return $this->redirectToRoute('app_event');
        }
        $form = $this->createForm( ModifyEventFormType::class, $events);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Mettre à jour l'artiste en base de données
            $entityManager->persist($events);
            $entityManager->flush();

            // Rediriger vers la liste des artistes après la modification
            return $this->redirectToRoute('app_event');
        }

        // Rendre la vue avec le formulaire
        return $this->render('event/modify.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/event/{{id}}', name: 'app_show_event')]
    public function info(EntityManagerInterface $entityManager, int $id): Response
    {
        $event = $entityManager->getRepository(Event::class)->find($id);

        // Rendre la vue avec le formulaire
        return $this->render('event/individualEvent.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/event/{id}/subscribe', name: 'app_subscribe_event')]
    public function register(Event $event, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            throw $this->createAccessDeniedException('Vous devez étre connecté.');
        }

        $event->addUser($user);
        $entityManager->flush();

        return $this->redirectToRoute('app_show_event', ['id' => $event->getId()]);
    }

    #[Route('/event/{id}/unsubscribe', name: 'app_unsubscribe_event')]
    public function unregister(Event $event, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            throw $this->createAccessDeniedException('Vous devez étre connecté.');
        }

        $event->removeUser($user);
        $entityManager->flush();

        return $this->redirectToRoute('app_show_event', ['id' => $event->getId()]);
    }
}

templates/event/create.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Ajoutez un événement</h1>
    {{ form_start(form) }}
    {{ form_row(form.name,{
        label:'Nom'
    }) }}
    {{ form_row(form.date,{
        label:'Date'
    }) }}
    {{ form_row(form.artist,{
        label:'Artiste'
    }) }}
    <button type="submit">Ajouter l'événement</button>
    {{ form_end(form) }}
{% endblock %}

templates/event/event.html.twig
{% extends "base.html.twig" %}

{% block body %}



    <p>Cherchez un évenement : </p>

    <form method="GET" action="{{ path('app_event') }}" class="event_form">
        <p>Du :</p>
        <input type="date" name="start_date" value="{{ app.request.get('start_date') }}">
        <p> Au:</p>
        <input type="date" name="end_date" value="{{ app.request.get('end_date') }}">
        <button type="submit">Submit</button>
    </form><br>

    <h1>Liste des événements</h1>
    <p>Ajoutez un événement <a href="{{ path('app_create_event') }}" ><img id="event_img_add" src="{{ asset('images/plus.png') }}" alt="add event"></a></p>


    <ul class="event_list">
        {% for event in events %}
            <li class="event_item">
                <a class="event_link" href="{{ path('app_show_event', {id: event.id}) }}" >{{ event.name }} </a><br>
            </li>

        {% endfor %}
    </ul>
{% endblock %}

templates/event/form-event.html.twig
{% extends "base.html.twig" %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.date) }}
    {{ form_row(form.artist) }}
    <button type="submit">Ajouter un événement</button>
    {{ form_end(form) }}
{% endblock %}

templates/event/individualEvent.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> {{ event.name }}</h1>

    <p class="Individual_event_id"><strong>ID :</strong> {{ event.id }}</p><br>

    <div class="Individual_event_info">
        <div class="Individual_event_section">
            <h3><i class="fas fa-calendar-alt"></i> Date de l'événement</h3>
            <p>{{ event.date|date('d/m/Y') }}</p>
        </div>


        <div class="Individual_event_section">
            <h3><i class="fas fa-user-alt"></i> Artiste</h3>
            {% if event.artist is not null %}
                <p><a href="{{ path('app_show_artist' , {id:event.artist.id}) }}">{{ event.artist.name }}</a></p><br>
            {% else %}
                <p> Pas encore d'artiste</p><br>
            {% endif %}
        </div>

        {% if app.user in event.follower %}
            <button onclick="window.location.href='{{ path('app_unsubscribe_event', {id: event.id}) }}'" class="button unsubscribe-btn">
                <i class="fas fa-user-minus"></i> Se désabonner
            </button>
        {% else %}
            <button onclick="window.location.href='{{ path('app_subscribe_event', {id: event.id}) }}'" class="button subscribe-btn">
                <i class="fas fa-user-plus"></i> S'abonner
            </button>
        {% endif %}

        {% if app.user.id == event.creator.id  %}
            <button class="button_remove" onclick="window.location.href='{{ path('app_delete_event', {id: event.id}) }}'">Supprimer</button>
            <button class="button_modify" onclick="window.location.href='{{ path('app_modify_event', {id: event.id}) }}'">Modifier</button>
        {% endif %}

        <button class="button_back" onclick="window.location.href='{{ path('app_event') }}'">
            <i class="fas fa-arrow-left"></i> Retour
        </button>
    </div>
{% endblock %}

templates/event/modify.html.twig
{% extends "base.html.twig" %}

{% block body %}

    {{ form_start(form) }}
        {{ form_row(form.name, {
            label: 'Nom'
        }) }}

        {{ form_row(form.date,{
            label:'Date'
        }) }}
        {{ form_row(form.artist,{
            label:'Artiste'
        }) }}
        <button type="submit">Modifier l'évènement</button>
    {{ form_end(form) }}
{% endblock %}

templates/event/modify2.html.twig
{% extends "base.html.twig" %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.date) }}
    {{ form_row(form.artist) }}
    <button type="submit">Modifier l'évènement</button>
    {{ form_end(form) }}
{% endblock %}